obj-$(CONFIG_BERLIN_PXA3XX_NFC) += pxa3xx_nand.o
pxa3xx_nand-y := pxa3xx_nand_debu.o hal_dhub.o
pxa3xx_nand-$(CONFIG_BERLIN_NAND_RANDOMIZER) += prbs15.o nand_randomizer.o
pxa3xx_nand-$(CONFIG_BERLIN_NAND_READ_RETRY) += pxa3xx_nand_read_retry_debu.o
