/* This file was generated by syncqt. */
#ifndef QT_QTSCRIPT_VERSION_H
#define QT_QTSCRIPT_VERSION_H

#define QTSCRIPT_VERSION_STR "5.8.0"

#define QTSCRIPT_VERSION 0x050800

#endif // QT_QTSCRIPT_VERSION_H
