/* This file was generated by syncqt. */
#ifndef QT_QTQUICK_VERSION_H
#define QT_QTQUICK_VERSION_H

#define QTQUICK_VERSION_STR "5.4.1"

#define QTQUICK_VERSION 0x050401

#endif // QT_QTQUICK_VERSION_H
