/* This file was generated by syncqt. */
#ifndef QT_QTUIPLUGIN_VERSION_H
#define QT_QTUIPLUGIN_VERSION_H

#define QTUIPLUGIN_VERSION_STR "5.8.0"

#define QTUIPLUGIN_VERSION 0x050800

#endif // QT_QTUIPLUGIN_VERSION_H
