.TH "opus_ctlvalues" 3 "Fri Jan 13 2023" "Version 1.3.1" "Opus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
opus_ctlvalues
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOPUS_AUTO\fP"
.br
.RI "Auto/default setting\&. "
.ti -1c
.RI "#define \fBOPUS_BITRATE_MAX\fP"
.br
.RI "Maximum bitrate\&. "
.ti -1c
.RI "#define \fBOPUS_APPLICATION_VOIP\fP"
.br
.RI "Best for most VoIP/videoconference applications where listening quality and intelligibility matter most\&. "
.ti -1c
.RI "#define \fBOPUS_APPLICATION_AUDIO\fP"
.br
.RI "Best for broadcast/high-fidelity application where the decoded audio should be as close as possible to the input\&. "
.ti -1c
.RI "#define \fBOPUS_APPLICATION_RESTRICTED_LOWDELAY\fP"
.br
.RI "Only use when lowest-achievable latency is what matters most\&. "
.ti -1c
.RI "#define \fBOPUS_SIGNAL_VOICE\fP   3001"
.br
.RI "Signal being encoded is voice\&. "
.ti -1c
.RI "#define \fBOPUS_SIGNAL_MUSIC\fP   3002"
.br
.RI "Signal being encoded is music\&. "
.ti -1c
.RI "#define \fBOPUS_BANDWIDTH_NARROWBAND\fP"
.br
.RI "4 kHz bandpass "
.ti -1c
.RI "#define \fBOPUS_BANDWIDTH_MEDIUMBAND\fP"
.br
.RI "6 kHz bandpass "
.ti -1c
.RI "#define \fBOPUS_BANDWIDTH_WIDEBAND\fP"
.br
.RI "8 kHz bandpass "
.ti -1c
.RI "#define \fBOPUS_BANDWIDTH_SUPERWIDEBAND\fP"
.br
.RI "12 kHz bandpass "
.ti -1c
.RI "#define \fBOPUS_BANDWIDTH_FULLBAND\fP"
.br
.RI "20 kHz bandpass "
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_ARG\fP   5000"
.br
.RI "Select frame size from the argument (default) "
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_2_5_MS\fP   5001"
.br
.RI "Use 2\&.5 ms frames\&. "
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_5_MS\fP   5002"
.br
.RI "Use 5 ms frames\&. "
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_10_MS\fP   5003"
.br
.RI "Use 10 ms frames\&. "
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_20_MS\fP   5004"
.br
.RI "Use 20 ms frames\&. "
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_40_MS\fP   5005"
.br
.RI "Use 40 ms frames\&. "
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_60_MS\fP   5006"
.br
.RI "Use 60 ms frames\&. "
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_80_MS\fP   5007"
.br
.RI "Use 80 ms frames\&. "
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_100_MS\fP   5008"
.br
.RI "Use 100 ms frames\&. "
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_120_MS\fP   5009"
.br
.RI "Use 120 ms frames\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBSee also:\fP
.RS 4
\fBGeneric CTLs\fP, \fBEncoder related CTLs\fP 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define OPUS_APPLICATION_AUDIO"

.PP
Best for broadcast/high-fidelity application where the decoded audio should be as close as possible to the input\&. 
.SS "#define OPUS_APPLICATION_RESTRICTED_LOWDELAY"

.PP
Only use when lowest-achievable latency is what matters most\&. Voice-optimized modes cannot be used\&. 
.SS "#define OPUS_APPLICATION_VOIP"

.PP
Best for most VoIP/videoconference applications where listening quality and intelligibility matter most\&. 
.SS "#define OPUS_AUTO"

.PP
Auto/default setting\&. 
.SS "#define OPUS_BANDWIDTH_FULLBAND"

.PP
20 kHz bandpass 
.SS "#define OPUS_BANDWIDTH_MEDIUMBAND"

.PP
6 kHz bandpass 
.SS "#define OPUS_BANDWIDTH_NARROWBAND"

.PP
4 kHz bandpass 
.SS "#define OPUS_BANDWIDTH_SUPERWIDEBAND"

.PP
12 kHz bandpass 
.SS "#define OPUS_BANDWIDTH_WIDEBAND"

.PP
8 kHz bandpass 
.SS "#define OPUS_BITRATE_MAX"

.PP
Maximum bitrate\&. 
.SS "#define OPUS_FRAMESIZE_100_MS   5008"

.PP
Use 100 ms frames\&. 
.SS "#define OPUS_FRAMESIZE_10_MS   5003"

.PP
Use 10 ms frames\&. 
.SS "#define OPUS_FRAMESIZE_120_MS   5009"

.PP
Use 120 ms frames\&. 
.SS "#define OPUS_FRAMESIZE_20_MS   5004"

.PP
Use 20 ms frames\&. 
.SS "#define OPUS_FRAMESIZE_2_5_MS   5001"

.PP
Use 2\&.5 ms frames\&. 
.SS "#define OPUS_FRAMESIZE_40_MS   5005"

.PP
Use 40 ms frames\&. 
.SS "#define OPUS_FRAMESIZE_5_MS   5002"

.PP
Use 5 ms frames\&. 
.SS "#define OPUS_FRAMESIZE_60_MS   5006"

.PP
Use 60 ms frames\&. 
.SS "#define OPUS_FRAMESIZE_80_MS   5007"

.PP
Use 80 ms frames\&. 
.SS "#define OPUS_FRAMESIZE_ARG   5000"

.PP
Select frame size from the argument (default) 
.SS "#define OPUS_SIGNAL_MUSIC   3002"

.PP
Signal being encoded is music\&. 
.SS "#define OPUS_SIGNAL_VOICE   3001"

.PP
Signal being encoded is voice\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Opus from the source code\&.
