.TH "opus_multistream_ctls" 3 "Mon Jan 23 2017" "Version 1.1.4" "Opus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
opus_multistream_ctls \- Multistream specific encoder and decoder CTLs
.PP
These are convenience macros that are specific to the \fBopus_multistream_encoder_ctl()\fP and \fBopus_multistream_decoder_ctl()\fP interface\&.  

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOPUS_MULTISTREAM_GET_ENCODER_STATE\fP(x,  y)"
.br
.RI "\fIGets the encoder state for an individual stream of a multistream encoder\&. \fP"
.ti -1c
.RI "#define \fBOPUS_MULTISTREAM_GET_DECODER_STATE\fP(x,  y)"
.br
.RI "\fIGets the decoder state for an individual stream of a multistream decoder\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
These are convenience macros that are specific to the \fBopus_multistream_encoder_ctl()\fP and \fBopus_multistream_decoder_ctl()\fP interface\&. 

The CTLs from \fBGeneric CTLs\fP, \fBEncoder related CTLs\fP, and \fBDecoder related CTLs\fP may be applied to a multistream encoder or decoder as well\&. In addition, you may retrieve the encoder or decoder state for an specific stream via \fBOPUS_MULTISTREAM_GET_ENCODER_STATE\fP or \fBOPUS_MULTISTREAM_GET_DECODER_STATE\fP and apply CTLs to it individually\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define OPUS_MULTISTREAM_GET_DECODER_STATE(x, y)"

.PP
Gets the decoder state for an individual stream of a multistream decoder\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP \fCopus_int32\fP: The index of the stream whose decoder you wish to retrieve\&. This must be non-negative and less than the \fCstreams\fP parameter used to initialize the decoder\&. 
.br
\fIy\fP \fCOpusDecoder**\fP: Returns a pointer to the given decoder state\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIOPUS_BAD_ARG\fP The index of the requested stream was out of range\&. 
.RE
.PP

.SS "#define OPUS_MULTISTREAM_GET_ENCODER_STATE(x, y)"

.PP
Gets the encoder state for an individual stream of a multistream encoder\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP \fCopus_int32\fP: The index of the stream whose encoder you wish to retrieve\&. This must be non-negative and less than the \fCstreams\fP parameter used to initialize the encoder\&. 
.br
\fIy\fP \fCOpusEncoder**\fP: Returns a pointer to the given encoder state\&. 
.RE
.PP
\fBReturn values:\fP
.RS 4
\fIOPUS_BAD_ARG\fP The index of the requested stream was out of range\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Opus from the source code\&.
