.TH "opus_ctlvalues" 3 "Mon Jan 23 2017" "Version 1.1.4" "Opus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
opus_ctlvalues \- Pre-defined values for CTL interface
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOPUS_AUTO\fP"
.br
.RI "\fIAuto/default setting\&. \fP"
.ti -1c
.RI "#define \fBOPUS_BITRATE_MAX\fP"
.br
.RI "\fIMaximum bitrate\&. \fP"
.ti -1c
.RI "#define \fBOPUS_APPLICATION_VOIP\fP"
.br
.RI "\fIBest for most VoIP/videoconference applications where listening quality and intelligibility matter most\&. \fP"
.ti -1c
.RI "#define \fBOPUS_APPLICATION_AUDIO\fP"
.br
.RI "\fIBest for broadcast/high-fidelity application where the decoded audio should be as close as possible to the input\&. \fP"
.ti -1c
.RI "#define \fBOPUS_APPLICATION_RESTRICTED_LOWDELAY\fP"
.br
.RI "\fIOnly use when lowest-achievable latency is what matters most\&. \fP"
.ti -1c
.RI "#define \fBOPUS_SIGNAL_VOICE\fP   3001"
.br
.RI "\fISignal being encoded is voice\&. \fP"
.ti -1c
.RI "#define \fBOPUS_SIGNAL_MUSIC\fP   3002"
.br
.RI "\fISignal being encoded is music\&. \fP"
.ti -1c
.RI "#define \fBOPUS_BANDWIDTH_NARROWBAND\fP"
.br
.RI "\fI4 kHz bandpass \fP"
.ti -1c
.RI "#define \fBOPUS_BANDWIDTH_MEDIUMBAND\fP"
.br
.RI "\fI6 kHz bandpass \fP"
.ti -1c
.RI "#define \fBOPUS_BANDWIDTH_WIDEBAND\fP"
.br
.RI "\fI8 kHz bandpass \fP"
.ti -1c
.RI "#define \fBOPUS_BANDWIDTH_SUPERWIDEBAND\fP"
.br
.RI "\fI12 kHz bandpass \fP"
.ti -1c
.RI "#define \fBOPUS_BANDWIDTH_FULLBAND\fP"
.br
.RI "\fI20 kHz bandpass \fP"
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_ARG\fP   5000"
.br
.RI "\fISelect frame size from the argument (default) \fP"
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_2_5_MS\fP   5001"
.br
.RI "\fIUse 2\&.5 ms frames\&. \fP"
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_5_MS\fP   5002"
.br
.RI "\fIUse 5 ms frames\&. \fP"
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_10_MS\fP   5003"
.br
.RI "\fIUse 10 ms frames\&. \fP"
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_20_MS\fP   5004"
.br
.RI "\fIUse 20 ms frames\&. \fP"
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_40_MS\fP   5005"
.br
.RI "\fIUse 40 ms frames\&. \fP"
.ti -1c
.RI "#define \fBOPUS_FRAMESIZE_60_MS\fP   5006"
.br
.RI "\fIUse 60 ms frames\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBSee also:\fP
.RS 4
\fBGeneric CTLs\fP, \fBEncoder related CTLs\fP 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define OPUS_APPLICATION_AUDIO"

.PP
Best for broadcast/high-fidelity application where the decoded audio should be as close as possible to the input\&. 
.SS "#define OPUS_APPLICATION_RESTRICTED_LOWDELAY"

.PP
Only use when lowest-achievable latency is what matters most\&. Voice-optimized modes cannot be used\&. 
.SS "#define OPUS_APPLICATION_VOIP"

.PP
Best for most VoIP/videoconference applications where listening quality and intelligibility matter most\&. 
.SS "#define OPUS_AUTO"

.PP
Auto/default setting\&. 
.SS "#define OPUS_BANDWIDTH_FULLBAND"

.PP
20 kHz bandpass 
.SS "#define OPUS_BANDWIDTH_MEDIUMBAND"

.PP
6 kHz bandpass 
.SS "#define OPUS_BANDWIDTH_NARROWBAND"

.PP
4 kHz bandpass 
.SS "#define OPUS_BANDWIDTH_SUPERWIDEBAND"

.PP
12 kHz bandpass 
.SS "#define OPUS_BANDWIDTH_WIDEBAND"

.PP
8 kHz bandpass 
.SS "#define OPUS_BITRATE_MAX"

.PP
Maximum bitrate\&. 
.SS "#define OPUS_FRAMESIZE_10_MS   5003"

.PP
Use 10 ms frames\&. 
.SS "#define OPUS_FRAMESIZE_20_MS   5004"

.PP
Use 20 ms frames\&. 
.SS "#define OPUS_FRAMESIZE_2_5_MS   5001"

.PP
Use 2\&.5 ms frames\&. 
.SS "#define OPUS_FRAMESIZE_40_MS   5005"

.PP
Use 40 ms frames\&. 
.SS "#define OPUS_FRAMESIZE_5_MS   5002"

.PP
Use 5 ms frames\&. 
.SS "#define OPUS_FRAMESIZE_60_MS   5006"

.PP
Use 60 ms frames\&. 
.SS "#define OPUS_FRAMESIZE_ARG   5000"

.PP
Select frame size from the argument (default) 
.SS "#define OPUS_SIGNAL_MUSIC   3002"

.PP
Signal being encoded is music\&. 
.SS "#define OPUS_SIGNAL_VOICE   3001"

.PP
Signal being encoded is voice\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Opus from the source code\&.
