.TH "opus_libinfo" 3 "Mon Jan 23 2017" "Version 1.1.4" "Opus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
opus_libinfo \- Opus library information functions
.SS "Functions"

.in +1c
.ti -1c
.RI "const char * \fBopus_strerror\fP (int error)"
.br
.RI "\fIConverts an opus error code into a human readable string\&. \fP"
.ti -1c
.RI "const char * \fBopus_get_version_string\fP (void)"
.br
.RI "\fIGets the libopus version string\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 

.SH "Function Documentation"
.PP 
.SS "const char* opus_get_version_string (void)"

.PP
Gets the libopus version string\&. Applications may look for the substring '-fixed' in the version string to determine whether they have a fixed-point or floating-point build at runtime\&.
.PP
\fBReturns:\fP
.RS 4
Version string 
.RE
.PP

.SS "const char* opus_strerror (int error)"

.PP
Converts an opus error code into a human readable string\&. 
.PP
\fBParameters:\fP
.RS 4
\fIerror\fP \fCint\fP: Error number 
.RE
.PP
\fBReturns:\fP
.RS 4
Error string 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Opus from the source code\&.
