.TH "opus_errorcodes" 3 "Fri Jan 13 2023" "Version 1.3.1" "Opus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
opus_errorcodes
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBOPUS_OK\fP"
.br
.RI "No error\&. "
.ti -1c
.RI "#define \fBOPUS_BAD_ARG\fP"
.br
.RI "One or more invalid/out of range arguments\&. "
.ti -1c
.RI "#define \fBOPUS_BUFFER_TOO_SMALL\fP"
.br
.RI "Not enough bytes allocated in the buffer\&. "
.ti -1c
.RI "#define \fBOPUS_INTERNAL_ERROR\fP"
.br
.RI "An internal error was detected\&. "
.ti -1c
.RI "#define \fBOPUS_INVALID_PACKET\fP"
.br
.RI "The compressed data passed is corrupted\&. "
.ti -1c
.RI "#define \fBOPUS_UNIMPLEMENTED\fP"
.br
.RI "Invalid/unsupported request number\&. "
.ti -1c
.RI "#define \fBOPUS_INVALID_STATE\fP"
.br
.RI "An encoder or decoder structure is invalid or already freed\&. "
.ti -1c
.RI "#define \fBOPUS_ALLOC_FAIL\fP"
.br
.RI "Memory allocation has failed\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define OPUS_ALLOC_FAIL"

.PP
Memory allocation has failed\&. 
.SS "#define OPUS_BAD_ARG"

.PP
One or more invalid/out of range arguments\&. 
.SS "#define OPUS_BUFFER_TOO_SMALL"

.PP
Not enough bytes allocated in the buffer\&. 
.SS "#define OPUS_INTERNAL_ERROR"

.PP
An internal error was detected\&. 
.SS "#define OPUS_INVALID_PACKET"

.PP
The compressed data passed is corrupted\&. 
.SS "#define OPUS_INVALID_STATE"

.PP
An encoder or decoder structure is invalid or already freed\&. 
.SS "#define OPUS_OK"

.PP
No error\&. 
.SS "#define OPUS_UNIMPLEMENTED"

.PP
Invalid/unsupported request number\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Opus from the source code\&.
