'\" -*- coding: UTF-8 -*-
.\" Copyright (C) 1998-2003 Miquel van Smoorenburg.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
.\"
.TH KILLALL5 8 "04 Nov 2003" "" "Linux System Administrator's Manual"
.SH NAME
killall5 -- send a signal to all processes.
.SH SYNOPSIS
.B killall5
.RB -signalnumber
.RB [ \-o
.IR omitpid[,omitpid..]]
.RB [ \-o
.IR omitpid[,omitpid..].. ]
.SH DESCRIPTION
.B killall5
is the SystemV killall command. It sends a signal to all processes except
kernel threads and the processes in its own session, so it won't kill
the shell that is running the script it was called from. Its primary
(only) use is in the \fBrc\fP scripts found in the /etc/init.d directory.
.SH OPTIONS
.IP "-o \fIomitpid\fP"
Tells \fIkillall5\fP to omit processes with that process id.
.SH NOTES
\fIkillall5\fP can also be invoked as pidof, which is simply a
(symbolic) link to the \fIkillall5\fP program.
.SH EXIT STATUS
The program return zero if it killed processes.  It return 2 if no
process were killed, and 1 if it was unable to find any processes
(/proc/ is missing).
.SH SEE ALSO
.BR halt (8),
.BR reboot (8),
.BR pidof (8)
.SH AUTHOR
Miquel van Smoorenburg, miquels@cistron.nl
