#define QT_FEATURE_sql_db2 -1
#define QT_FEATURE_sql_ibase -1
#define QT_FEATURE_sql_mysql -1
#define QT_FEATURE_sql_oci -1
#define QT_FEATURE_sql_odbc -1
#define QT_FEATURE_sql_psql -1
#define QT_FEATURE_sql_sqlite 1
#define QT_FEATURE_sql_sqlite2 -1
#define QT_FEATURE_sql_tds -1
