#!/bin/sh

FACTORY_DIR=/mnt/factory_setting
SERIAL_NUMBER_FILE=${FACTORY_DIR}/box_serial

serial=$(cat $SERIAL_NUMBER_FILE|tr -d '\n' |tail -c4)
name=$(cat /etc/hostname)

if [ -z "$serial" ]; then
        hostname $name
else
        hostname $name-$serial
fi
