#!/bin/sh

rm -f /var/run/dbus/system_bus_socket
rm -f /var/run/dbus/pid
/usr/bin/dbus-daemon --system --fork

# Start session bus for pulseaudio
export HOME=/home/steam
dbus-daemon --fork --session --print-address > /tmp/DBUS_SESSION_BUS_ADDRESS
