#!/bin/sh
#
# Script to start sshd if desired

if [ -f /mnt/config/system/enable_ssh.txt ]; then
	# Generate ssh keys if necessary
	if [ ! -f /etc/ssh_host_rsa_key ]; then
		ssh-keygen -A
	fi

	# Set root password if needed
	if grep -q "root::" /etc/passwd; then
		passwd root <<__EOF__
steamlink123
steamlink123
__EOF__
	fi

	/usr/sbin/sshd
fi
