#!/bin/sh
if ! base=$(realpath "$0" 2>/dev/null); then
  case $0 in
  /*) base=$0;;
  *)  base=${PWD:-`pwd`}/$0;;
  esac
fi
basedir=${base%/*}
exec   "${basedir}/../../../../../../lib/ld-linux-x86-64.so.2"   --library-path "${basedir}/../../../../../../lib"   --inhibit-rpath ''   "${base}.elf"   "$@"
