/* This file was generated by syncqt. */
#ifndef QT_QT3DRENDER_VERSION_H
#define QT_QT3DRENDER_VERSION_H

#define QT3DRENDER_VERSION_STR "5.8.0"

#define QT3DRENDER_VERSION 0x050800

#endif // QT_QT3DRENDER_VERSION_H
