# Add your debugging flag (or not) to CFLAGS

obj-$(CONFIG_BERLIN_CC) += cc.o

cc-objs := cc_driver.o cc_std_map.o cc_list.o cc_cbuf_body.o cc_cbuf_server.o \
                    cc_dss.o cc_udp.o cc_msgq.o
