
# __LINUX_KERNEL__ is used in OS-independent header files
MV_DEFINE := -DBERLIN -DSoC_Galois -D__LINUX_KERNEL__ -D__CODE_LINK__=0 -DCPUINDEX=0
MV_DEFINE += -DBERLIN_B_0=0x1000 -DBERLIN_C_0=0x2000 -DBERLIN_BG2=0x3000 -DBERLIN_BG2_Z2=0x3010 -DBERLIN_BG2_A0=0x3020 -DBERLIN_BG2CD_A0=0x3100 -DBERLIN_BG3=0x4000

# define BERLIN_CHIP_VERSION
ifeq ($(CONFIG_BERLIN2_Z1),y)
	MV_DEFINE += -DBERLIN_CHIP_VERSION=BERLIN_BG2
	FIRMWARE = Firmware_Berlin_BG2
endif
ifeq ($(CONFIG_BERLIN2_Z2),y)
	MV_DEFINE += -DBERLIN_CHIP_VERSION=BERLIN_BG2_Z2
	FIRMWARE = Firmware_Berlin_BG2_Z2
endif
ifeq ($(CONFIG_BERLIN2_A0),y)
	MV_DEFINE += -DBERLIN_CHIP_VERSION=BERLIN_BG2_A0
	FIRMWARE = Firmware_Berlin_BG2_A0
endif
ifeq ($(CONFIG_BERLIN2CD),y)
	MV_DEFINE += -DBERLIN_CHIP_VERSION=BERLIN_BG2CD_A0
	FIRMWARE = Firmware_Berlin_BG2CD_A0
endif
ifeq ($(CONFIG_BERLIN2_CT),y)
	MV_DEFINE += -DBERLIN_CHIP_VERSION=BERLIN_BG2_A0
	FIRMWARE = Firmware_Berlin_BG2_CT
endif
ifeq ($(CONFIG_ARCH_BERLIN3),y)
	MV_DEFINE += -DBERLIN_CHIP_VERSION=BERLIN_BG3
	FIRMWARE = Firmware_Berlin_BG3
endif

